service:
  name: serverless-alexa-ts

plugins:
  - serverless-webpack
  # - serverless-dynamodb-local # uncomment to use dynamodb local

custom:
  webpack:
    webpackConfig: 'webpack.config.ts'
  # dynamodb: # uncomment to use dynamodb local
  #   start:
  #     port: 8100

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: ${file(./config/config.yml):${self:provider.stage}.memorySize, '256'}
  timeout: 60
  stage: ${opt:stage, 'develop'}
  region: ap-northeast-1
  # iamRoleStatements: # uncomment to use dynamodb
  #   - Effect: "Allow"
  #     Action:
  #       - dynamodb:DescribeTable
  #       - dynamodb:CreateTable
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/alexa-user-attrs-${self:provider.stage}"

functions:
  handler:
    handler: index.handler
    events:
      - alexaSkill: ${file(./config/config.yml):${self:provider.stage}.alexa.SKILL_ID}
    environment:
      TZ: ${file(./config/config.yml):${self:provider.stage}.timezone}
      SKILL_ID: ${file(./config/config.yml):${self:provider.stage}.alexa.SKILL_ID}
      # ATTRIBUTES_DB: alexa-user-attrs-${self:provider.stage} # uncomment to use dynamodb

